# Generated by Django 5.0.4 on 2024-07-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_user_is_calling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_calling',
            field=models.BooleanField(default=False),
        ),
    ]
