# Generated by Django 5.0.4 on 2024-07-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0003_alter_user_is_calling'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_a_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
